name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3) Cache npm dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4) Optional: Install Chrome (if your App Service doesn't already have it)
      - name: Install system Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # 5) Install dependencies without downloading Chromium
      - name: Install dependencies
        working-directory: back-end
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'

      # 6) Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: CS330-2025-01-Group04-backend   # replace if needed
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: back-end
