name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main           # Trigger on push to demo2 branch
  workflow_dispatch:    # Allow manual run from GitHub Actions UI

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
      # Step 1: Check out your repo
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js (needed to build React app)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install frontend dependencies
      - name: Install dependencies
        run: npm install
        working-directory: front-end   # <-- make sure this matches your folder

      # Step 4: Build the React app
      - name: Build the React app
        run: npm run build
        working-directory: front-end

      # Step 5: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: front-end                  # <-- Source directory
          output_location: .                # <-- React build output folder
