name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # or 'demo2' if you're using that branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repo
      - uses: actions/checkout@v3

      # Step 2: Deploy static site to Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: front-end       # <-- this is the folder with index.html
          output_location: .            # <-- no build step, use . as output
